# -*- coding: utf-8 -*-
"""Copy of day-10 python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FVp3_ARV9YDqiTjjpQxVwyeolx2OU2AL
"""

#String Methods and Slicing
# Ask the user to input a sentence (feedback)
feedback = input("Enter your feedback: ")

# Count how many words are in the sentence
# split() breaks the sentence by spaces and returns a list of words
word_count = len(feedback.split())
print("Total number of words:", word_count)

# Count how many times the word “data” appears (case-insensitive)
# Convert to lower case so that Data, DATA, data = all same
data_count = feedback.lower().count("data")
print("Number of times 'data' appears:", data_count)

# Extract and print first 5 and last 5 characters
first_five = feedback[:5]     # slicing from start to 5th character
last_five = feedback[-5:]     # slicing last 5 characters
print("First 5 characters:", first_five)
print("Last 5 characters:", last_five)

# Reverse the sentence and print it
reversed_feedback = feedback[::-1]  # slicing with step -1 reverses the string
print("Reversed sentence:", reversed_feedback)