# -*- coding: utf-8 -*-
"""day-9 python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C8-Ky7U3tzGqGGZDIcBFiRR7MREo0DsH
"""

# Step 1: Create variables to store student details
student_name = input("Enter the student's name: ")
student_age = int(input("Enter the student's age: "))
favourite_subjects = input("Enter your favourite subjects: ")

# Step 2: Display the student’s information
print("\n--- Student Information ---")
print(f"Name: {student_name}")
print(f"Age: {student_age}")
print(f"Favourite Subjects: {favourite_subjects}")

# Step 3: Ask the student to enter a new favourite subject
new_subject = input("\nEnter a new favourite subject to add: ")

# Step 4: Display the updated list of subjects
print("\n--- Updated Student Information ---")
print(f"Name: {student_name}")
print(f"Age: {student_age}")
print(f"Updated Favourite Subjects: {favourite_subjects}{', '}{new_subject}")